### DISCUSSION TITLE
メッセージ投稿後またはリルート後、自分のサーバーからの投稿が全て"failed to fetch"になります。

### DISCUSSION THREAD

**Discussion by ouroboros723** [concrnt/concrnt-square#12] [Q&A] [answered]
最初はユーザー数増加による過負荷と思ったのですが、LAN上のリバースプロキシのログを確認したところ、Concrntサーバーから大量の429レスポンスが発生していることがわかりました。

下記一部リバースプロキシのログ抜粋

```
...
106.146.29.176 - - [18/Jan/2025:16:30:28 +0900] "GET /api/v1/message/ms4xwx7vwjbvmnfda06a7gjvrh0/associationcounts?schema=https%3A%2F%2Fschema.concrnt.world%2Fa%2Freaction.json HTTP/1.1" 429 20 "https://develop.concurrent-world-cya.pages.dev/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36" "-""-" "-" "-" - 
106.146.29.176 - - [18/Jan/2025:16:30:28 +0900] "GET /api/v1/message/mjtfndwresnp9w6p206a7gjrf9r/associationcounts?schema=https%3A%2F%2Fschema.concrnt.world%2Fa%2Freaction.json HTTP/1.1" 429 20 "https://develop.concurrent-world-cya.pages.dev/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36" "-""-" "-" "-" - 
106.146.29.176 - - [18/Jan/2025:16:30:28 +0900] "GET /api/v1/message/m5qtxs8pt1bxgasaj06a7gjywcw/associationcounts?schema=https%3A%2F%2Fschema.concrnt.world%2Fa%2Freaction.json HTTP/1.1" 429 20 "https://develop.concurrent-world-cya.pages.dev/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36" "-""-" "-" "-" - 
106.146.29.176 - - [18/Jan/2025:16:30:29 +0900] "GET /api/v1/message/mr2vmswcqawch0nmf06a7gm4eq4/associationcounts HTTP/1.1" 429 20 "https://develop.concurrent-world-cya.pages.dev/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36" "-""-" "-" "-" - 
121.107.13.59 - - [18/Jan/2025:16:30:34 +0900] "GET /api/v1/message/mh151tc86hxpma9ms06a7gkkp88/associationcounts?schema=https%3A%2F%2Fschema.concrnt.world%2Fa%2Freaction.json HTTP/1.1" 429 20 "https://concrnt.world/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-""-" "-" "-" - 
121.107.13.59 - - [18/Jan/2025:16:30:34 +0900] "GET /api/v1/message/mr2vmswcqawch0nmf06a7gm4eq4/associationcounts?schema=https%3A%2F%2Fschema.concrnt.world%2Fa%2Freaction.json HTTP/1.1" 429 20 "https://concrnt.world/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-""-" "-" "-" - 
121.107.13.59 - - [18/Jan/2025:16:30:34 +0900] "GET /api/v1/message/mr779v14bhayhc19m06a7gkdf6m/associationcounts?schema=https%3A%2F%2Fschema.concrnt.world%2Fa%2Freaction.json HTTP/1.1" 429 20 "https://concrnt.world/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-""-" "-" "-" - 
121.107.13.59 - - [18/Jan/2025:16:30:34 +0900] "GET /api/v1/message/m783q6v1xsz2nmzj306a7gk6zyw/associationcounts?schema=https%3A%2F%2Fschema.concrnt.world%2Fa%2Freaction.json HTTP/1.1" 429 20 "https://concrnt.world/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-""-" "-" "-" - 
115.37.119.165 - - [18/Jan/2025:16:30:36 +0900] "GET /api/v1/message/m3affb9ffpx2pea6306a7gcf3yc/associationcounts HTTP/1.1" 429 20 "https://concrnt.world/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0" "-""-" "-" "-" - 
...
```

もしかして、Concrnt側に何らかのレートリミット設定があるのでしょうか。
ちなみに、[kustomize](https://github.com/concrnt/concrnt-kustomize.git)を使用して構築しています。

**Comment by totegamma** [comment]
引っ掛かってそうなのはassociationcountsみたい


```
> 01/18 16:53 ~/cgo$ curl https://valdra.cc.draboros.net/api/v1/message/mg4tpav42b82ry34r06a7gs7w9c/associationcounts -i
HTTP/1.1 200 OK
Date: Sat, 18 Jan 2025 07:53:20 GMT
Content-Type: application/json
Content-Length: 29
Connection: keep-alive
Vary: Accept-Encoding
Cc-Service: net.concrnt.api
Vary: Origin
X-Ratelimit-Limit: 1000
X-Ratelimit-Remaining: 43
Strict-Transport-Security: max-age=31536000

{"content":{},"status":"ok"}
> 01/18 16:53 ~/cgo$
```

**Comment by totegamma** [comment]
config的には存在してるので本当にアクセスされまくったってことなのかな

https://github.com/totegamma/concurrent/blob/develop/_docs/etc/config/gateway.yaml#L37

**Comment by totegamma** [comment]
サンプル設定だとバースト1000で1秒に1回復なのでそんなに使い果たすことなさそうだけどな

**Comment by ouroboros723** [comment]
ありがとうございます。
どのように修正すれば良いでしょうか？
現在のgateway.yamlです。


```
services:
  - name: net.concrnt.webui
    host: ccwebui
    port: 80
    path: /web
    preservePath: true
  - name: net.concrnt.api
    host: ccapi
    port: 8000
    path: /api/v1
    injectCors: true
    rateLimit:
      'GET:/api/v1/domain':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/domain/:id':
        bucketSize: 10
        refillSpan: 1
      'GET:/api/v1/domains':
        bucketSize: 10
        refillSpan: 1

      'GET:/api/v1/entity/:id':
        bucketSize: 1000
        refillSpan: 1
      'GET:/api/v1/entity/:id/acking':
        bucketSize: 10
        refillSpan: 1
      'GET:/api/v1/entity/:id/acker':
        bucketSize: 10
        refillSpan: 1
      'GET:/api/v1/entity/:id/entities':
        bucketSize: 10
        refillSpan: 1

      'GET:/api/v1/message/:id':
        bucketSize: 1000
        refillSpan: 1
      'GET:/api/v1/message/:id/associations':
        bucketSize: 1000
        refillSpan: 1
      'GET:/api/v1/message/:id/associationcounts':
        bucketSize: 1000
        refillSpan: 1
      'GET:/api/v1/message/:id/associations/mine':
        bucketSize: 1000
        refillSpan: 1

      'GET:/api/v1/association/:id':
        bucketSize: 1000
        refillSpan: 1

      'GET:/api/v1/profile/:id':
        bucketSize: 1000
        refillSpan: 1
      'GET:/api/v1/profile/:owner/:semanticid':
        bucketSize: 1000
        refillSpan: 1
      'GET:/api/v1/profiles':
        bucketSize: 10
        refillSpan: 1
      'GET:/api/v1/profile/:id/associations':
        bucketSize: 100
        refillSpan: 1

      'GET:/api/v1/timeline/:id':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/timeline/:id/query':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/timeline/:id/associations':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/timelines':
        bucketSize: 10
        refillSpan: 1
      'GET:/api/v1/timelines/mine':
        bucketSize: 10
        refillSpan: 1
      'GET:/api/v1/timelines/recent':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/timelines/range':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/timelines/chunks':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/timelines/retracted':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/timelines/realtime':
        bucketSize: 10
        refillSpan: 1

      'GET:/api/v1/chunks/itr':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/chunks/body':
        bucketSize: 100
        refillSpan: 1

      'GET:/api/v1/kv/:key':
        bucketSize: 100
        refillSpan: 1
      'PUT:/api/v1/kv/:key':
        bucketSize: 100
        refillSpan: 1

      'GET:/api/v1/auth/passport':
        bucketSize: 30
        refillSpan: 1

      'GET:/api/v1/key/:id':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/keys/mine':
        bucketSize: 10
        refillSpan: 1

      'GET:/api/v1/subscription/:id':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/subscription/:id/associations':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/subscriptions/mine':
        bucketSize: 10
        refillSpan: 1

      'GET:/api/v1/repository':
        bucketSize: 100
        refillSpan: 1
      'POST:/api/v1/repository':
        bucketSize: 100
        refillSpan: 1
      'GET:/api/v1/repositories/sync':
        bucketSize: 10
        refillSpan: 1
      'POST:/api/v1/repositories/sync':
        bucketSize: 10
        refillSpan: 1

      'GET:/api/v1/jobs':
        bucketSize: 10
        refillSpan: 1
      'POST:/api/v1/jobs':
        bucketSize: 10
        refillSpan: 1
      'DELETE:/api/v1/job/:id':
        bucketSize: 10
        refillSpan: 1

      'POST:/api/v1/commit':
        bucketSize: 30
        refillSpan: 5

      'DEFAULT':
        bucketSize: 100
        refillSpan: 1
  - name: world.concrnt.ap-bridge
    host: ccactivitypub
    port: 8000
    path: /ap
    preservePath: true
    injectCors: true
  - name: world.concrnt.webfinger
    host: ccactivitypub
    port: 8000
    path: /.well-known
    preservePath: true
  - name: world.concrnt.hyperproxy.summary
    host: hyperproxy
    port: 8000
    path: /summary
    preservePath: true
  - name: world.concrnt.hyperproxy.image
    host: hyperproxy
    port: 8000
    path: /image
    preservePath: true
```

ちなみに、投稿のリルート時に、リバースプロキシのログには大量のアクセスログが発生します。
何か関係があるかもしれません。
